apiVersion: v1
kind: Service
metadata:
  name: finance-tracker-service
  namespace: finance-tracker
  labels:
    app: finance-tracker
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: finance-tracker
