apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: finance-tracker-hpa
  namespace: finance-tracker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: finance-tracker
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
